name: HCPROJECT WEB

on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2    
    - name: Restore dependencies           
      run: dotnet restore HCProject/HCProject.sln 
    - name: HCProject Publish
      run: |
        sudo systemctl stop kestrel-hcproject.service
        dotnet publish HCProject/HCProject.sln -c release -o /var/www/hcproject
        sudo systemctl start kestrel-hcproject.service
