name: HCPROJECT WEB

on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2    
    - name: Restore dependencies           
      run: dotnet restore    
    - name: HCProject Web Publish
      run: |
        sudo systemctl stop kestrel-hcproject.service
        dotnet publish -c Release -o /var/www/test
        sudo systemctl start kestrel-hcproject.service
