name: HCPROJECT WEB

on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2    
    - name: Restore dependencies           
      run: dotnet restore HCProject/HCProject.sln
    - name: HCProject Build
      run: |
        sudo systemctl stop kestrel-hcproject.service
        dotnet build HCProject/HCProject.sln
        sudo systemctl start kestrel-hcproject.service
